### ISSUE TITLE
Please remove 'node-red' keyword until ready for general use

### ISSUE THREAD

**Issue by knolleary** [isaacvitor/node-red-contrib-socketio-client#1]
Hi,

Given the warning you provide in the readme, can I suggest you remove the `node-red` keyword from your `package.json` file? This will cause it to be unlisted from https://flows.nodered.org.

Once your node is ready for general use, publish a version with the keyword added back in and it will get picked up by the library.

Thanks,
Nick

**Comment by isaacvitor** [comment]
Hi,

I removed the keyword, (how you can see in actual version) but on https://flows.nodered.org still show the module.
How can I help to solved this?

**Comment by isaacvitor** [comment]
Sorry I maked a mistake... Now is correct!
