### ISSUE TITLE
Not getting events...

### ISSUE THREAD

**Issue by ScottChapman** [isaacvitor/node-red-contrib-socketio-client#2]
So, I have a simple node.js app. I am trying to emit an event to socket.io and pick it up in node red. My endpoint looks like:
```
app.post('/turnOnLights', jsonParser, function (req, res) {
  if (!req.body) return res.sendStatus(400);
  io.sockets.emit("TurnOnLight","turn on my light!");
  res.send({status: "All set!"}).status(200).end();
})
```

I created a connector node, and a listener node connected to the connector node. But I am not seeing any events as far as I can tell...

**Comment by isaacvitor** [comment]
Hi @ScottChapman 

I needed to remove the key-work "node-red" because of this you can not install from https://flows.nodered.org.
But you can install through the `npm i node-red-contrib-socketio-client`
The version 0.2.0 is ok to use.

**Comment by ScottChapman** [comment]
I did install via npm. Did your recent change fix my problem?
