### ISSUE TITLE
Emit

### ISSUE THREAD

**Issue by lucasmellos** [isaacvitor/node-red-contrib-socketio-client#4]
Do you plan to release an emitter function?

**Comment by isaacvitor** [comment]
Good question @lucasmellos! Probably I can do it whether you need very much but before a correct response I need to make a look at the module

**Comment by lucasmellos** [comment]
I'm planning use your module in a research project. I need three basic functions: (1) listener, (2) connector and (3) emitter to send response messages.

The project objective is receive messages, identify the events and response with a new message.

**Comment by isaacvitor** [comment]
Ok, good! I will see what I can do soon... I'll stay with this issue open to remember me...

**Comment by lucasmellos** [comment]
Any date to release the new feature?

**Comment by isaacvitor** [comment]
Hi @lucasmellos I've been problems with time in my life, but I believe that I'll find a solution until then end of month.
Did you try to use the native module websocket to solve what you want?

**Comment by aryeharmon** [comment]
@lucasmellos @isaacvitor  added this feature in pull request

**Comment by lucasmellos** [comment]
Thanks @aryeharmon. I'm really excited to test this feature.

**Comment by isaacvitor** [comment]
I really sorry because I'm working a lot and didn't spend time to add this feature. Thanks @aryeharmon and @lucasmellos
